version: '3.2'
services:
  web:
    build:
      context: ./flask-app
      dockerfile: Dockerfile
    restart: always
    ports:
     - "5000:5000"
    depends_on:
      - redis
  worker:
    build:
      context: ./flask-celery
      dockerfile: Dockerfile
    depends_on:
      - redis
  monitor:
    build:
      context: ./flask-celery
      dockerfile: Dockerfile
    ports:
     - "5555:5555"
    entrypoint: flower
    command:  -A tasks --port=5555 --broker=redis://redis:6379/0
    depends_on:
      - redis
  redis:
    image: redis
